const db = require('./database');

// Categories
const categories = [
  { name: 'Software Engineering', icon: '💻' },
  { name: 'Data Science', icon: '📊' },
  { name: 'Product Design', icon: '🎨' },
  { name: 'Product Management', icon: '📋' },
  { name: 'Marketing', icon: '📣' },
  { name: 'Sales', icon: '💰' },
  { name: 'DevOps & Cloud', icon: '☁️' },
  { name: 'Mobile Development', icon: '📱' },
  { name: 'AI & Machine Learning', icon: '🤖' },
  { name: 'Cybersecurity', icon: '🔒' },
  { name: 'Finance & Accounting', icon: '📈' },
  { name: 'Human Resources', icon: '🤝' },
];

// Insert categories
const insertCat = db.prepare('INSERT OR IGNORE INTO categories (name, icon) VALUES (?, ?)');
const insertCats = db.transaction(() => {
  for (const cat of categories) {
    insertCat.run(cat.name, cat.icon);
  }
});
insertCats();

console.log('✅ Categories seeded');

// Jobs
const jobs = [
  {
    title: 'Senior Frontend Engineer',
    company: 'Google',
    company_logo: 'https://logo.clearbit.com/google.com',
    location: 'Mountain View, CA',
    type: 'Full-Time',
    work_mode: 'Hybrid',
    category: 'Software Engineering',
    salary_min: 180000,
    salary_max: 260000,
    currency: 'USD',
    description: 'Join Google\'s frontend team to build next-generation web experiences used by billions. You\'ll work on cutting-edge web technologies and help define the future of the web platform.',
    requirements: 'Bachelor\'s in CS or equivalent;5+ years frontend experience;Expert in React, TypeScript;Strong understanding of web performance;Experience with large-scale applications',
    responsibilities: 'Lead frontend architecture decisions;Mentor junior engineers;Build and ship user-facing features;Collaborate with UX designers;Conduct code reviews',
    skills: 'React,TypeScript,JavaScript,HTML,CSS,GraphQL,Web Performance',
    experience_level: 'Senior',
    is_featured: 1,
    deadline: '2026-06-30'
  },
  {
    title: 'Machine Learning Intern',
    company: 'OpenAI',
    company_logo: 'https://logo.clearbit.com/openai.com',
    location: 'San Francisco, CA',
    type: 'Internship',
    work_mode: 'On-site',
    category: 'AI & Machine Learning',
    salary_min: 8000,
    salary_max: 12000,
    currency: 'USD',
    description: 'Work on cutting-edge AI research at OpenAI. This internship offers hands-on experience with large language models and reinforcement learning from human feedback.',
    requirements: 'Currently pursuing MS/PhD in CS or related;Strong Python skills;Experience with PyTorch or TensorFlow;Published research is a plus',
    responsibilities: 'Conduct ML experiments;Analyze model performance;Write technical reports;Collaborate with research scientists;Present findings to the team',
    skills: 'Python,PyTorch,TensorFlow,Machine Learning,NLP,Deep Learning',
    experience_level: 'Entry Level',
    is_featured: 1,
    deadline: '2026-05-15'
  },
  {
    title: 'Full Stack Developer',
    company: 'Stripe',
    company_logo: 'https://logo.clearbit.com/stripe.com',
    location: 'Seattle, WA',
    type: 'Full-Time',
    work_mode: 'Remote',
    category: 'Software Engineering',
    salary_min: 160000,
    salary_max: 220000,
    currency: 'USD',
    description: 'Build the economic infrastructure of the internet. Work on Stripe\'s payment platform handling billions in transactions for millions of businesses worldwide.',
    requirements: 'Bachelor\'s in CS or equivalent;3+ years full stack experience;Proficiency in Ruby or Python;Experience with distributed systems;Strong problem-solving skills',
    responsibilities: 'Design and implement APIs;Build internal tools;Improve system reliability;Write comprehensive tests;Participate in on-call rotation',
    skills: 'Ruby,Python,JavaScript,React,PostgreSQL,Redis,AWS',
    experience_level: 'Mid Level',
    is_featured: 1,
    deadline: '2026-07-01'
  },
  {
    title: 'Product Design Intern',
    company: 'Figma',
    company_logo: 'https://logo.clearbit.com/figma.com',
    location: 'San Francisco, CA',
    type: 'Internship',
    work_mode: 'Hybrid',
    category: 'Product Design',
    salary_min: 6000,
    salary_max: 9000,
    currency: 'USD',
    description: 'Design the tools that designers use every day. Join Figma\'s design team and shape the future of collaborative design software.',
    requirements: 'Pursuing degree in Design, HCI, or related;Strong portfolio;Proficiency in Figma;Understanding of design systems;Passion for design tools',
    responsibilities: 'Create high-fidelity mockups;Conduct user research;Iterate on designs based on feedback;Build prototypes;Present design proposals',
    skills: 'Figma,UI Design,UX Research,Prototyping,Design Systems,Interaction Design',
    experience_level: 'Entry Level',
    is_featured: 1,
    deadline: '2026-05-30'
  },
  {
    title: 'Backend Engineer',
    company: 'Spotify',
    company_logo: 'https://logo.clearbit.com/spotify.com',
    location: 'Stockholm, Sweden',
    type: 'Full-Time',
    work_mode: 'Hybrid',
    category: 'Software Engineering',
    salary_min: 90000,
    salary_max: 140000,
    currency: 'EUR',
    description: 'Help build the systems that power music streaming for 600M+ users. Work on recommendation engines, audio processing pipelines, and real-time data infrastructure.',
    requirements: 'Bachelor\'s in CS or equivalent;4+ years backend experience;Strong Java or Scala skills;Experience with microservices;Knowledge of data streaming',
    responsibilities: 'Design microservices architecture;Build data pipelines;Optimize system performance;Collaborate with data scientists;Ensure high availability',
    skills: 'Java,Scala,Kafka,Kubernetes,GCP,Microservices,gRPC',
    experience_level: 'Mid Level',
    is_featured: 0,
    deadline: '2026-06-15'
  },
  {
    title: 'Data Science Intern',
    company: 'Netflix',
    company_logo: 'https://logo.clearbit.com/netflix.com',
    location: 'Los Gatos, CA',
    type: 'Internship',
    work_mode: 'On-site',
    category: 'Data Science',
    salary_min: 7500,
    salary_max: 10000,
    currency: 'USD',
    description: 'Work on Netflix\'s recommendation algorithms and A/B testing platform. Help personalize the entertainment experience for 250M+ subscribers.',
    requirements: 'Pursuing MS/PhD in Statistics, CS, or related;Strong Python/R skills;Experience with statistical modeling;SQL proficiency',
    responsibilities: 'Analyze user behavior data;Build predictive models;Design A/B experiments;Create data visualizations;Present insights to stakeholders',
    skills: 'Python,R,SQL,Statistics,Machine Learning,A/B Testing,Tableau',
    experience_level: 'Entry Level',
    is_featured: 1,
    deadline: '2026-05-20'
  },
  {
    title: 'DevOps Engineer',
    company: 'Amazon',
    company_logo: 'https://logo.clearbit.com/amazon.com',
    location: 'Arlington, VA',
    type: 'Full-Time',
    work_mode: 'On-site',
    category: 'DevOps & Cloud',
    salary_min: 150000,
    salary_max: 210000,
    currency: 'USD',
    description: 'Build and manage cloud infrastructure at scale. Work on AWS services that power millions of businesses worldwide.',
    requirements: 'Bachelor\'s in CS or equivalent;5+ years DevOps experience;Expert in AWS;Strong scripting skills;Experience with IaC tools',
    responsibilities: 'Design CI/CD pipelines;Manage cloud infrastructure;Implement monitoring solutions;Automate deployments;Ensure security compliance',
    skills: 'AWS,Terraform,Docker,Kubernetes,Python,Bash,CI/CD,Monitoring',
    experience_level: 'Senior',
    is_featured: 0,
    deadline: '2026-07-15'
  },
  {
    title: 'iOS Developer',
    company: 'Apple',
    company_logo: 'https://logo.clearbit.com/apple.com',
    location: 'Cupertino, CA',
    type: 'Full-Time',
    work_mode: 'On-site',
    category: 'Mobile Development',
    salary_min: 175000,
    salary_max: 250000,
    currency: 'USD',
    description: 'Build the apps that define mobile experiences. Work on iOS system apps used by over a billion people around the world.',
    requirements: 'Bachelor\'s in CS or equivalent;4+ years iOS development;Expert in Swift and SwiftUI;Published apps on App Store;Knowledge of Apple frameworks',
    responsibilities: 'Design and build iOS features;Optimize app performance;Collaborate with hardware teams;Write unit and UI tests;Review pull requests',
    skills: 'Swift,SwiftUI,UIKit,Xcode,Core Data,Combine,iOS',
    experience_level: 'Mid Level',
    is_featured: 0,
    deadline: '2026-06-30'
  },
  {
    title: 'Product Manager',
    company: 'Meta',
    company_logo: 'https://logo.clearbit.com/meta.com',
    location: 'Menlo Park, CA',
    type: 'Full-Time',
    work_mode: 'Hybrid',
    category: 'Product Management',
    salary_min: 190000,
    salary_max: 280000,
    currency: 'USD',
    description: 'Define the future of social connection. Lead product strategy for features used by billions of people on Facebook, Instagram, and WhatsApp.',
    requirements: 'MBA or BS in CS;5+ years PM experience;Experience with consumer products;Strong analytical skills;Excellent communication',
    responsibilities: 'Define product roadmap;Analyze user metrics;Collaborate with engineering;Conduct user research;Present to leadership',
    skills: 'Product Strategy,Data Analysis,User Research,Agile,SQL,Roadmapping',
    experience_level: 'Senior',
    is_featured: 1,
    deadline: '2026-06-15'
  },
  {
    title: 'Cybersecurity Analyst',
    company: 'CrowdStrike',
    company_logo: 'https://logo.clearbit.com/crowdstrike.com',
    location: 'Austin, TX',
    type: 'Full-Time',
    work_mode: 'Remote',
    category: 'Cybersecurity',
    salary_min: 120000,
    salary_max: 170000,
    currency: 'USD',
    description: 'Protect organizations from the most sophisticated cyber threats. Analyze attack patterns and develop detection strategies for advanced persistent threats.',
    requirements: 'Bachelor\'s in Cybersecurity or CS;3+ years security experience;CISSP or equivalent cert;Incident response experience;Knowledge of threat intelligence',
    responsibilities: 'Monitor security alerts;Investigate incidents;Develop detection rules;Conduct threat hunting;Write security reports',
    skills: 'SIEM,Threat Intelligence,Incident Response,Python,Malware Analysis,Network Security',
    experience_level: 'Mid Level',
    is_featured: 0,
    deadline: '2026-07-01'
  },
  {
    title: 'Marketing Intern',
    company: 'HubSpot',
    company_logo: 'https://logo.clearbit.com/hubspot.com',
    location: 'Boston, MA',
    type: 'Internship',
    work_mode: 'Hybrid',
    category: 'Marketing',
    salary_min: 4000,
    salary_max: 5500,
    currency: 'USD',
    description: 'Learn growth marketing from the leaders in inbound marketing. Work on campaigns that reach millions of businesses worldwide.',
    requirements: 'Pursuing degree in Marketing or Business;Strong writing skills;Familiarity with social media platforms;Analytical mindset;Creative thinking',
    responsibilities: 'Create content for social media;Analyze campaign metrics;Assist with email marketing;Conduct market research;Support event planning',
    skills: 'Content Marketing,Social Media,SEO,Google Analytics,Email Marketing,Copywriting',
    experience_level: 'Entry Level',
    is_featured: 0,
    deadline: '2026-05-31'
  },
  {
    title: 'Android Developer',
    company: 'Samsung',
    company_logo: 'https://logo.clearbit.com/samsung.com',
    location: 'Seoul, South Korea',
    type: 'Full-Time',
    work_mode: 'On-site',
    category: 'Mobile Development',
    salary_min: 80000,
    salary_max: 130000,
    currency: 'USD',
    description: 'Build next-generation mobile experiences for Samsung\'s flagship devices. Work on custom Android features and Samsung OneUI enhancements.',
    requirements: 'Bachelor\'s in CS;3+ years Android development;Strong Kotlin skills;Experience with Jetpack Compose;Knowledge of Android internals',
    responsibilities: 'Develop Android features;Optimize battery performance;Build custom UI components;Test on multiple devices;Collaborate with firmware team',
    skills: 'Kotlin,Jetpack Compose,Android SDK,Java,Room,Coroutines',
    experience_level: 'Mid Level',
    is_featured: 0,
    deadline: '2026-06-30'
  },
  {
    title: 'Cloud Solutions Architect',
    company: 'Microsoft',
    company_logo: 'https://logo.clearbit.com/microsoft.com',
    location: 'Redmond, WA',
    type: 'Full-Time',
    work_mode: 'Hybrid',
    category: 'DevOps & Cloud',
    salary_min: 170000,
    salary_max: 240000,
    currency: 'USD',
    description: 'Design cloud architectures on Azure for enterprise customers. Help the world\'s largest organizations modernize their infrastructure.',
    requirements: 'Bachelor\'s in CS or equivalent;7+ years cloud experience;Azure certifications;Architecture design skills;Customer-facing experience',
    responsibilities: 'Design cloud architectures;Lead technical workshops;Create reference implementations;Advise on best practices;Build proof of concepts',
    skills: 'Azure,Cloud Architecture,Terraform,Docker,Kubernetes,.NET,Solution Design',
    experience_level: 'Lead',
    is_featured: 1,
    deadline: '2026-07-30'
  },
  {
    title: 'UX Researcher',
    company: 'Airbnb',
    company_logo: 'https://logo.clearbit.com/airbnb.com',
    location: 'San Francisco, CA',
    type: 'Full-Time',
    work_mode: 'Remote',
    category: 'Product Design',
    salary_min: 140000,
    salary_max: 190000,
    currency: 'USD',
    description: 'Uncover insights that shape how people travel and host around the world. Conduct research that directly impacts Airbnb\'s product decisions.',
    requirements: 'Master\'s in HCI, Psychology, or related;4+ years UX research;Mixed methods expertise;Experience with enterprise research;Strong presentation skills',
    responsibilities: 'Plan and conduct user studies;Analyze qualitative & quantitative data;Create research reports;Present findings to product teams;Build research frameworks',
    skills: 'User Research,Usability Testing,Survey Design,Data Analysis,Figma,Research Ops',
    experience_level: 'Mid Level',
    is_featured: 0,
    deadline: '2026-06-15'
  },
  {
    title: 'Financial Analyst Intern',
    company: 'Goldman Sachs',
    company_logo: 'https://logo.clearbit.com/goldmansachs.com',
    location: 'New York, NY',
    type: 'Internship',
    work_mode: 'On-site',
    category: 'Finance & Accounting',
    salary_min: 7000,
    salary_max: 9500,
    currency: 'USD',
    description: 'Begin your career in finance at one of the world\'s leading investment banks. Work alongside seasoned professionals on real deal analyses and market research.',
    requirements: 'Pursuing degree in Finance, Economics, or related;Strong Excel skills;Knowledge of financial modeling;Attention to detail;Team player',
    responsibilities: 'Build financial models;Prepare client presentations;Conduct market research;Analyze financial statements;Support deal teams',
    skills: 'Financial Modeling,Excel,PowerPoint,Bloomberg,Valuation,Accounting',
    experience_level: 'Entry Level',
    is_featured: 0,
    deadline: '2026-05-01'
  },
  {
    title: 'HR Business Partner',
    company: 'Salesforce',
    company_logo: 'https://logo.clearbit.com/salesforce.com',
    location: 'San Francisco, CA',
    type: 'Full-Time',
    work_mode: 'Hybrid',
    category: 'Human Resources',
    salary_min: 130000,
    salary_max: 180000,
    currency: 'USD',
    description: 'Shape the employee experience at one of the best places to work. Partner with business leaders to build high-performing, inclusive teams.',
    requirements: 'Bachelor\'s in HR or Business;5+ years HRBP experience;Knowledge of employment law;Experience with HRIS systems;Strong coaching skills',
    responsibilities: 'Advise managers on people strategy;Lead organizational design;Drive performance management;Support talent planning;Analyze workforce data',
    skills: 'HR Strategy,Talent Management,Employee Relations,Coaching,Workday,HR Analytics',
    experience_level: 'Senior',
    is_featured: 0,
    deadline: '2026-06-30'
  },
  {
    title: 'React Native Developer',
    company: 'Uber',
    company_logo: 'https://logo.clearbit.com/uber.com',
    location: 'San Francisco, CA',
    type: 'Full-Time',
    work_mode: 'Hybrid',
    category: 'Mobile Development',
    salary_min: 155000,
    salary_max: 215000,
    currency: 'USD',
    description: 'Build the mobile experiences that move the world. Work on the Uber rider and driver apps used by millions of people daily.',
    requirements: 'Bachelor\'s in CS;3+ years React Native experience;Strong JavaScript/TypeScript;Experience with native modules;Performance optimization skills',
    responsibilities: 'Build cross-platform features;Optimize app performance;Implement real-time features;Write comprehensive tests;Mentor junior developers',
    skills: 'React Native,TypeScript,JavaScript,Redux,Native Modules,CI/CD',
    experience_level: 'Mid Level',
    is_featured: 0,
    deadline: '2026-07-15'
  },
  {
    title: 'Data Engineer',
    company: 'Snowflake',
    company_logo: 'https://logo.clearbit.com/snowflake.com',
    location: 'Bozeman, MT',
    type: 'Full-Time',
    work_mode: 'Remote',
    category: 'Data Science',
    salary_min: 145000,
    salary_max: 200000,
    currency: 'USD',
    description: 'Build the data cloud. Work on large-scale data infrastructure that powers analytics for thousands of organizations.',
    requirements: 'Bachelor\'s in CS or equivalent;4+ years data engineering;Strong SQL skills;Experience with Spark or similar;Knowledge of data modeling',
    responsibilities: 'Design data pipelines;Optimize query performance;Build ETL processes;Ensure data quality;Document data architectures',
    skills: 'SQL,Python,Spark,Airflow,dbt,Snowflake,Data Modeling',
    experience_level: 'Mid Level',
    is_featured: 0,
    deadline: '2026-06-30'
  },
  {
    title: 'Sales Development Representative',
    company: 'Notion',
    company_logo: 'https://logo.clearbit.com/notion.so',
    location: 'New York, NY',
    type: 'Full-Time',
    work_mode: 'Hybrid',
    category: 'Sales',
    salary_min: 65000,
    salary_max: 90000,
    currency: 'USD',
    description: 'Help teams discover the power of connected workspaces. Be at the forefront of Notion\'s enterprise growth strategy.',
    requirements: 'Bachelor\'s degree;1+ years sales experience;Excellent communication;CRM experience;Self-motivated',
    responsibilities: 'Prospect new accounts;Qualify inbound leads;Conduct discovery calls;Schedule demos;Track pipeline metrics',
    skills: 'Sales,Salesforce,Cold Outreach,Communication,Lead Qualification,SaaS',
    experience_level: 'Entry Level',
    is_featured: 0,
    deadline: '2026-06-15'
  },
  {
    title: 'Software Engineering Intern',
    company: 'Tesla',
    company_logo: 'https://logo.clearbit.com/tesla.com',
    location: 'Palo Alto, CA',
    type: 'Internship',
    work_mode: 'On-site',
    category: 'Software Engineering',
    salary_min: 6500,
    salary_max: 9500,
    currency: 'USD',
    description: 'Work on software that powers electric vehicles and sustainable energy products. Contribute to Tesla\'s mission to accelerate the world\'s transition to sustainable energy.',
    requirements: 'Pursuing BS/MS in CS or EE;Strong C++ or Python;Interest in automotive software;Problem-solving aptitude;Passion for sustainability',
    responsibilities: 'Develop embedded software;Write automated tests;Debug vehicle systems;Collaborate with hardware engineers;Document code',
    skills: 'C++,Python,Embedded Systems,Linux,Git,Testing',
    experience_level: 'Entry Level',
    is_featured: 1,
    deadline: '2026-05-15'
  },
  {
    title: 'AI Research Scientist',
    company: 'DeepMind',
    company_logo: 'https://logo.clearbit.com/deepmind.com',
    location: 'London, UK',
    type: 'Full-Time',
    work_mode: 'Hybrid',
    category: 'AI & Machine Learning',
    salary_min: 130000,
    salary_max: 200000,
    currency: 'GBP',
    description: 'Push the boundaries of artificial intelligence. Work on fundamental research that transforms our understanding of intelligence and impacts millions of lives.',
    requirements: 'PhD in CS, Math, or Neuroscience;Published papers at top venues;Strong coding skills;Deep knowledge of ML theory;Research track record',
    responsibilities: 'Conduct original research;Publish at top conferences;Develop novel architectures;Collaborate with research teams;Mentor PhD interns',
    skills: 'PyTorch,JAX,Reinforcement Learning,Transformers,Research,Python,Mathematics',
    experience_level: 'Senior',
    is_featured: 1,
    deadline: '2026-08-01'
  },
  {
    title: 'Growth Marketing Manager',
    company: 'Shopify',
    company_logo: 'https://logo.clearbit.com/shopify.com',
    location: 'Toronto, Canada',
    type: 'Full-Time',
    work_mode: 'Remote',
    category: 'Marketing',
    salary_min: 100000,
    salary_max: 140000,
    currency: 'CAD',
    description: 'Drive merchant growth for the world\'s leading commerce platform. Build and optimize marketing funnels that help entrepreneurs succeed.',
    requirements: 'Bachelor\'s in Marketing or Business;4+ years growth marketing;Experience with paid acquisition;Strong analytics skills;A/B testing expertise',
    responsibilities: 'Plan growth campaigns;Optimize conversion funnels;Manage ad budgets;Analyze marketing ROI;Lead cross-functional projects',
    skills: 'Growth Marketing,Google Ads,Facebook Ads,Analytics,A/B Testing,SEO,SEM',
    experience_level: 'Mid Level',
    is_featured: 0,
    deadline: '2026-06-30'
  },
  {
    title: 'Blockchain Developer',
    company: 'Coinbase',
    company_logo: 'https://logo.clearbit.com/coinbase.com',
    location: 'Remote',
    type: 'Full-Time',
    work_mode: 'Remote',
    category: 'Software Engineering',
    salary_min: 165000,
    salary_max: 230000,
    currency: 'USD',
    description: 'Build the future of the open financial system. Work on core blockchain infrastructure and decentralized protocols at scale.',
    requirements: 'Bachelor\'s in CS;3+ years blockchain development;Solidity experience;Understanding of DeFi protocols;Cryptography knowledge',
    responsibilities: 'Develop smart contracts;Build blockchain integrations;Audit code for security;Design protocol upgrades;Write technical documentation',
    skills: 'Solidity,Ethereum,Web3.js,Go,Rust,Smart Contracts,Cryptography',
    experience_level: 'Mid Level',
    is_featured: 0,
    deadline: '2026-07-15'
  },
  {
    title: 'QA Engineering Intern',
    company: 'Adobe',
    company_logo: 'https://logo.clearbit.com/adobe.com',
    location: 'San Jose, CA',
    type: 'Internship',
    work_mode: 'Hybrid',
    category: 'Software Engineering',
    salary_min: 5500,
    salary_max: 8000,
    currency: 'USD',
    description: 'Ensure quality in creative tools used by millions. Learn testing best practices while working on Adobe\'s flagship products.',
    requirements: 'Pursuing BS in CS or related;Knowledge of testing methodologies;Basic scripting skills;Attention to detail;Analytical mindset',
    responsibilities: 'Write automated tests;Execute test plans;Report and track bugs;Participate in sprint planning;Improve test coverage',
    skills: 'Selenium,Python,Java,Test Automation,JIRA,Agile,API Testing',
    experience_level: 'Entry Level',
    is_featured: 0,
    deadline: '2026-05-30'
  },
  {
    title: 'Technical Program Manager',
    company: 'LinkedIn',
    company_logo: 'https://logo.clearbit.com/linkedin.com',
    location: 'Sunnyvale, CA',
    type: 'Full-Time',
    work_mode: 'Hybrid',
    category: 'Product Management',
    salary_min: 170000,
    salary_max: 240000,
    currency: 'USD',
    description: 'Drive complex technical programs that connect the world\'s professionals. Coordinate cross-functional efforts across engineering, design, and data science.',
    requirements: 'Bachelor\'s in CS or Engineering;6+ years TPM experience;PMP or similar cert preferred;Strong technical acumen;Stakeholder management skills',
    responsibilities: 'Lead cross-team programs;Manage project timelines;Identify and mitigate risks;Drive technical decisions;Report to leadership',
    skills: 'Program Management,Agile,JIRA,Technical Architecture,Risk Management,Stakeholder Management',
    experience_level: 'Lead',
    is_featured: 0,
    deadline: '2026-07-01'
  }
];

const insertJob = db.prepare(`
  INSERT INTO jobs (title, company, company_logo, location, type, work_mode, category_id, salary_min, salary_max, currency, description, requirements, responsibilities, skills, experience_level, is_featured, deadline)
  VALUES (?, ?, ?, ?, ?, ?, (SELECT id FROM categories WHERE name = ?), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`);

const insertJobs = db.transaction(() => {
  for (const job of jobs) {
    insertJob.run(
      job.title, job.company, job.company_logo, job.location, job.type, job.work_mode,
      job.category, job.salary_min, job.salary_max, job.currency,
      job.description, job.requirements, job.responsibilities, job.skills,
      job.experience_level, job.is_featured, job.deadline
    );
  }
});

insertJobs();
console.log(`✅ ${jobs.length} jobs seeded`);
console.log('\n🎉 Database seeded successfully!\n');
